import { useEffect, useState, type ReactNode } from 'react';
import type { Assessment, Rating, YesNoUnsure } from './types';
import { childhood, createAssessment, demoAssessment, differential, executive, hyperactivity, impairment, inattention, settings } from './data';
import { RatingScale } from './components/RatingScale';
import { Report } from './components/Report';
import './styles.css';

const storage = 'axis-clinical-learning-v2';
const steps = ['Welcome','Participant profile','Inattention','Hyperactivity / impulsivity','Duration & childhood','Settings & impact','Other factors','Review','Results'];

type ContextKey = 'settings' | 'impairment' | 'executive' | 'differential';
const frequencyHelp = 'Choose the answer that best matches your typical experience. Think about your usual pattern, not only your best or worst day.';

export default function App() {
  const [step, setStep] = useState(0);
  const [student, setStudent] = useState(false);
  const [a, setA] = useState<Assessment>(() => { try { return JSON.parse(localStorage.getItem(storage) || '') as Assessment; } catch { return createAssessment(); } });
  useEffect(() => localStorage.setItem(storage, JSON.stringify(a)), [a]);
  const update = (fn: (current: Assessment) => Assessment) => setA(fn);
  const clear = () => { if (confirm('Clear all locally saved assessment responses?')) { localStorage.removeItem(storage); setA(createAssessment()); setStep(0); } };
  const next = () => {
    if (step === 1 && !a.user.age && !a.user.dob) return alert('Enter your age or date of birth to continue.');
    if (step === 4 && !a.duration) return alert('Choose how long these difficulties have generally been present, or choose “Not sure”.');
    if (step === 4 && Object.keys(a.childhood).length < childhood.length) return alert('Please answer the childhood questions. If you do not remember, choose “Not sure”.');
    setStep(s => Math.min(s + 1, steps.length - 1));
  };
  const percentage = Math.round(step / (steps.length - 1) * 100);
  const contextSection = (key: ContextKey, title: string, intro: string, items: { title: string; explanation?: string }[], labels: string[]) => page(title, intro, <div>{items.map((item, i) => <div className="rating-item" key={item.title}><b>{item.title}</b>{item.explanation && <p className="help-text">{item.explanation}</p>}<RatingScale labels={labels} value={a[key][i] || 0} onChange={value => update(c => ({ ...c, [key]: { ...c[key], [i]: value } }))}/></div>)}</div>);
  let body: ReactNode;
  if (step === 0) body = <><div className="eyebrow">Educational clinical reasoning tool</div><h1>Understand the pattern, not just the score.</h1><p className="lede">A structured educational simulation that brings symptom frequency, developmental history, settings, functioning, and other relevant factors together.</p><div className="intro"><b>Important:</b> This is not a diagnostic test. It is an educational tool based on the structure of DSM-5-TR ADHD criteria and should not replace a qualified clinician.</div><div className="hero-meta"><span><b>Clear questions</b>Clinical terms explained in plain English</span><span><b>Structured evidence</b>Symptoms, development, settings & impact</span><span><b>Transparent report</b>See why each finding appears</span></div><div className="actions"><button className="link" onClick={() => { setA(demoAssessment()); setStep(8); }}>Open fictional demo</button><button onClick={next}>Begin assessment</button></div></>;
  else if (step === 1) body = page('Participant profile','Age changes the educational symptom-count threshold. Identifiers are optional and responses are saved locally in this browser.', <div className="form-grid">{[['Name / optional identifier','name','text'],['How old are you?','age','number'],['Date of birth (optional)','dob','date'],['Current role / occupation','role','text'],['Education level','education','text'],['Country','country','text']].map(([label,key,type]) => <label key={key}>{label}<input type={type} value={a.user[key as keyof typeof a.user]} onChange={e => update(c => ({ ...c, user: { ...c.user, [key]: e.target.value } }))}/></label>)}</div>);
  else if (step === 2 || step === 3) {
    const domain = step === 2 ? 'inattentive' : 'hyperactive'; const questions = step === 2 ? inattention : hyperactivity;
    body = page(step === 2 ? 'Inattention' : 'Hyperactivity / impulsivity', step === 2 ? 'These questions describe attention, organisation, follow-through, and forgetfulness.' : 'These questions describe restlessness, activity level, talking, waiting, and interrupting.', <>
      <div className="note"><b>How to answer:</b> {frequencyHelp}<div className="scale-guide"><span><b>Never</b> generally does not happen</span><span><b>Rarely</b> happens occasionally</span><span><b>Sometimes</b> happens from time to time</span><span><b>Often</b> happens regularly</span><span><b>Very often</b> happens very frequently</span></div></div>
      {questions.map((q,i) => { const s = a[domain][i]; return <fieldset className="symptom" key={q.title}><legend>{i + 1}. {q.title}</legend><p className="help-text">{q.explanation}</p><RatingScale value={s.rating} onChange={rating => update(c => { const list = [...c[domain]]; list[i] = { ...list[i], rating }; return { ...c, [domain]: list }; })}/><label>Optional example or consequence<textarea placeholder="Add a short example if helpful…" value={s.example} onChange={e => update(c => { const list = [...c[domain]]; list[i] = { ...list[i], example: e.target.value }; return { ...c, [domain]: list }; })}/></label></fieldset>; })}
    </>);
  } else if (step === 4) body = page('Duration & developmental history','This section asks about persistence and whether similar difficulties were present before age 12. “Not sure” is a valid answer.', <>
    <div className="explain-box"><b>Why ask about childhood?</b><p>ADHD is a neurodevelopmental condition. The DSM-5-TR asks whether several symptoms were present before age 12. Adult memories can be incomplete, so do not guess.</p></div>
    <label className="wide">How long have these difficulties generally been present?<select value={a.duration} onChange={e => update(c => ({ ...c, duration: e.target.value }))}><option value="">Select one</option>{['Less than 3 months','3–6 months','6–12 months','1–3 years','More than 3 years','Since childhood','Not sure'].map(x => <option key={x}>{x}</option>)}</select></label>
    <h3>Before age 12, were there significant difficulties involving:</h3><p className="help-text">Choose Yes, No, or Not sure. These are prompts for developmental history, not a childhood diagnosis.</p>
    {childhood.map((x,i) => <div className="child-row" key={x}><div><b>{x}</b><small>{childhoodHelp(x)}</small></div><div>{(['Yes','No','Unsure'] as YesNoUnsure[]).map(value => <label key={value}><input type="radio" checked={a.childhood[i] === value} onChange={() => update(c => ({ ...c, childhood: { ...c.childhood, [i]: value } }))}/>{value === 'Unsure' ? 'Not sure' : value}</label>)}</div></div>)}
    <label className="wide">Childhood examples, observations, or records (optional)<textarea value={a.childNotes} onChange={e => update(c => ({ ...c, childNotes: e.target.value }))}/></label>
  </>);
  else if (step === 5) body = <>{contextSection('settings','Settings & functional impact','The DSM-5-TR considers whether symptoms occur across more than one setting and whether they interfere with everyday functioning. These questions describe context; they do not automatically establish a criterion.', settings.map(title => ({ title, explanation: settingHelp(title) })), ['Not at all','Slightly','Sometimes','Often','Very much'])}<h3>Functional impact</h3>{contextSection('impairment','How much do these difficulties affect you?','Think about actual interference with day-to-day functioning. A higher impact rating is not an ADHD diagnosis.', impairment.map(title => ({ title, explanation: impairmentHelp(title) })), ['Not affected','Slight','Moderate','Marked','Severe'])}</>;
  else if (step === 6) body = <>{contextSection('differential','Other factors that can affect attention','Sleep problems, mood, anxiety, stress, substances, learning differences, medical factors, and medications can affect attention or activity. These questions identify factors worth discussing with a professional.', differential, ['Not at all','Slightly','Sometimes','Often','Very much'])}<div className="note"><b>These are not diagnoses.</b> A flagged factor means it may deserve context or professional exploration; it does not mean that factor is causing your difficulties.</div><h3>Supplementary executive functioning</h3><p className="help-text">These questions are contextual only. Executive-function difficulty is not used as the core ADHD symptom count.</p>{contextSection('executive','Everyday executive functioning','Rate how difficult these areas feel in daily life.', executive.map(title => ({ title })), ['Not at all','Slightly','Sometimes','Often','Very much'])}</>;
  else if (step === 7) body = page('Review & optional observer','Check your responses. You can add another person’s perspective, but it is completely optional.', <><div className="note"><b>Optional observer perspective:</b> A parent, partner, teacher, friend, or employer may provide useful context. You can skip this completely.</div><div className="form-grid"><label>Observer type (optional)<select value={a.collateral.type} onChange={e => update(c => ({ ...c, collateral: { ...c.collateral, type: e.target.value } }))}><option value="">Skip — not available</option>{['Parent','Partner','Teacher','Friend','Employer','Other'].map(x => <option key={x}>{x}</option>)}</select></label><label className="full">Observer notes (optional)<textarea value={a.collateral.note} onChange={e => update(c => ({ ...c, collateral: { ...c.collateral, note: e.target.value } }))}/></label></div><div className="review-grid"><div><b>Inattention</b><span>{a.inattentive.filter(s => s.rating >= 3).length}/9 threshold-level responses</span></div><div><b>Hyperactivity / impulsivity</b><span>{a.hyperactive.filter(s => s.rating >= 3).length}/9 threshold-level responses</span></div><div><b>Childhood history</b><span>{Object.keys(a.childhood).length}/13 answered</span></div><div><b>Duration</b><span>{a.duration || 'Not selected'}</span></div></div></>);
  else body = <Report assessment={a} onClear={clear}/>;
  return <><header><div className="brand"><span>A</span><div>Axis Clinical Learning<small>ADHD assessment simulator</small></div></div><label className="student"><input type="checkbox" checked={student} onChange={e => setStudent(e.target.checked)}/> Student guidance</label></header><main className={student ? 'student-mode' : ''}>{step === 8 ? body : <div className="shell"><aside><div className="rail"><div className="eyebrow">Structured assessment</div><h3>Assessment pathway</h3><div className="progress"><i style={{ width: `${percentage}%` }}/></div><p><span>Progress</span><b>{percentage}%</b></p><ol>{steps.map((s,i) => <li key={s} className={i === step ? 'active' : i < step ? 'done' : ''}>{s}</li>)}</ol></div></aside><section className="sheet"><span className="section-number">{String(step).padStart(2,'0')} / {steps[step]}</span>{body}<div className="actions">{step > 0 && <button className="secondary" onClick={() => setStep(s => s - 1)}>Back</button>}{step < 8 && <button onClick={next}>Continue</button>}</div></section></div>}</main><footer>Educational assessment and clinical-reasoning simulation — not a diagnostic device. A qualified clinician must make any diagnosis or treatment decision.</footer></>;
}

function page(title: string, description: string, children: ReactNode) { return <><h2>{title}</h2><p className="lede">{description}</p>{children}</>; }
function childhoodHelp(x: string) { const m: Record<string,string> = {'Attention / focus':'For example, often losing focus in class, reading, homework, or other activities.','Homework completion':'For example, regularly leaving schoolwork unfinished or needing unusually frequent reminders.','Forgetfulness':'For example, frequently forgetting homework, instructions, belongings, or commitments.','Losing school supplies':'For example, often misplacing books, pencils, bags, or other school materials.','Daydreaming':'For example, frequently appearing mentally elsewhere during class or conversations.','Following instructions':'For example, struggling to follow multi-step directions even when you understood them.','Restlessness':'For example, frequently needing to move, fidget, or leave your seat.','Talking excessively':'For example, talking much more than expected in class or other situations.','Interrupting':'For example, regularly speaking over people or answering before they finish.','Impulsivity':'For example, acting quickly without considering consequences or difficulty waiting.','Organisation':'For example, difficulty keeping school materials, assignments, or routines organised.','Academic inconsistency':'For example, work quality or completion varying greatly despite similar ability.','Behavioural difficulties':'For example, repeated concerns about impulsive, restless, disruptive, or difficult-to-manage behaviour.'}; return m[x]; }
function settingHelp(x: string) { return x === 'Home & routines' ? 'Think about chores, routines, family interactions, and everyday tasks at home.' : x === 'School / university' ? 'Think about lectures, studying, assignments, attendance, deadlines, and classroom situations.' : x === 'Workplace' ? 'Think about meetings, deadlines, organisation, task completion, and staying focused at work.' : x === 'Relationships & social life' ? 'Think about conversations, listening, turn-taking, commitments, and social interactions.' : 'Think about errands, appointments, personal projects, finances, or other responsibilities.'; }
function impairmentHelp(x: string) { const m: Record<string,string> = {'Academic / study performance':'Missing deadlines, leaving work unfinished, struggling to study, or performing below your ability.','Work performance':'Missed deadlines, unfinished tasks, disorganisation, or inconsistent performance.','Relationships':'Forgetting commitments, interrupting, difficulty listening, conflict, or other relationship effects.','Household responsibilities':'Difficulty keeping up with chores, routines, errands, or shared responsibilities.','Time management':'Frequently underestimating time, running late, or struggling to sequence tasks.','Financial management':'Forgetting bills, losing track of spending, or difficulty organising financial responsibilities.','Driving / safety':'Difficulty staying attentive, impulsive decisions, or other safety-related problems.','Daily self-management':'Difficulty maintaining routines, appointments, medication schedules, sleep routines, or other self-care tasks.'}; return m[x]; }
