import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import type { Assessment, Rating } from './types';
import { childhood, createAssessment, demoAssessment, differential, executive, hyperactivity, impairment, inattention, settings } from './data';
import { RatingScale, Slider } from './components/RatingScale';
import { Report } from './components/Report';
import './styles.css';
const storage='axis-clinical-learning-v1';
const steps=['Welcome','Participant profile','Inattention','Hyperactivity / impulsivity','Developmental history','Settings & impairment','Executive functioning','Differential considerations','Collateral information','Response review','Results & report'];
type Key='settings'|'impairment'|'executive'|'differential';
export default function App(){const [step,setStep]=useState(0),[student,setStudent]=useState(false),[a,setA]=useState<Assessment>(()=>{try{return JSON.parse(localStorage.getItem(storage)||'') as Assessment}catch{return createAssessment()}});useEffect(()=>localStorage.setItem(storage,JSON.stringify(a)),[a]);const update=(fn:(current:Assessment)=>Assessment)=>setA(fn);const clear=()=>{if(confirm('Clear this locally stored assessment?')){localStorage.removeItem(storage);setA(createAssessment());setStep(0)}};const next=()=>{if(step===1&&!a.user.age&&!a.user.dob){alert('Enter age or date of birth to continue.');return}setStep(s=>Math.min(s+1,steps.length-1))};const percentage=Math.round(step/(steps.length-1)*100);const slider=(key:Key,title:string,items:string[])=>page(title,'0 = none / not reported · 4 = severe or strongly affecting.',<>{items.map((x,i)=><Slider key={x} label={x} value={a[key][i]||0} onChange={value=>update(c=>({...c,[key]:{...c[key],[i]:value}}))}/>)}</>);let body:ReactNode;
if(step===0)body=<><div className="eyebrow">Educational clinical reasoning tool</div><h1>Understanding assessment beyond a checklist.</h1><p className="lede">A deliberate simulation of how clinicians bring together symptom pattern, developmental history, functioning, context, and alternatives when assessing ADHD.</p><div className="intro"><b>Screening is not diagnosis.</b> This tool demonstrates the reasoning process. It cannot diagnose ADHD and never replaces a qualified clinician’s assessment.</div><div className="hero-meta"><span><b>Symptom pattern</b>Two domains, item by item</span><span><b>Clinical context</b>Development, impairment & settings</span><span><b>Transparent reasoning</b>See what supports each finding</span></div><div className="actions"><button className="link" onClick={()=>{setA(demoAssessment());setStep(10)}}>Open fictional demo</button><button onClick={next}>Begin assessment</button></div></>;
else if(step===1)body=page('Participant profile','Age changes the educational threshold. Identifiers are optional and stored only in this browser.',<div className="form-grid">{[['Name / optional identifier','name','text'],['How old are you?','age','number'],['Date of birth (optional)','dob','date'],['Current role / occupation','role','text'],['Education level','education','text'],['Country','country','text'],['Assessment date','date','date']].map(([label,key,type])=><label key={key}>{label}<input type={type} value={a.user[key as keyof typeof a.user]} onChange={e=>update(c=>({...c,user:{...c.user,[key]:e.target.value}}))}/></label>)}</div>);
else if(step===2||step===3){const domain=step===2?'inattentive':'hyperactive',questions=step===2?inattention:hyperactivity;body=page(step===2?'Inattention':'Hyperactivity / impulsivity','Rate frequency in a typical period. Examples add context, but do not independently establish a clinical symptom.',<><div className="note"><b>Educational counting rule:</b> ratings of Often or Very often are considered threshold-level. Context, persistence, developmental appropriateness, and impairment also matter.</div>{questions.map((q,i)=>{const s=a[domain][i];return <fieldset className="symptom" key={q}><legend>{i+1}. {q}</legend><RatingScale value={s.rating} onChange={rating=>update(c=>{const list=[...c[domain]];list[i]={...list[i],rating};return {...c,[domain]:list}})}/><div className="symptom-fields"><label>Reported duration<select value={s.duration} onChange={e=>update(c=>{const list=[...c[domain]];list[i]={...list[i],duration:e.target.value};return {...c,[domain]:list}})}><option value="">Not recorded</option><option>6+ months</option><option>1+ years</option><option>Since childhood</option></select></label><label>Optional example or consequence<textarea value={s.example} onChange={e=>update(c=>{const list=[...c[domain]];list[i]={...list[i],example:e.target.value};return {...c,[domain]:list}})} /></label></div></fieldset>})}</>)}
else if(step===4)body=page('Duration & developmental history','ADHD is understood as neurodevelopmental. Clinicians seek developmental evidence while recognising that adult recall can be unclear.',<><label className="wide">How long have these difficulties been present?<select value={a.duration} onChange={e=>update(c=>({...c,duration:e.target.value}))}><option value="">Select duration</option>{['Less than 3 months','3–6 months','6–12 months','1–3 years','More than 3 years','Since childhood','Unsure'].map(x=><option key={x}>{x}</option>)}</select></label><h3>Before age 12, were there difficulties involving:</h3>{childhood.map((x,i)=><div className="child-row" key={x}><b>{x}</b><div>{['Yes','No','Unsure'].map(value=><label key={value}><input type="radio" checked={a.childhood[i]===value} onChange={()=>update(c=>({...c,childhood:{...c.childhood,[i]:value}}))}/>{value}</label>)}</div></div>)}<label className="wide">Childhood examples, observations, or records<textarea value={a.childNotes} onChange={e=>update(c=>({...c,childNotes:e.target.value}))}/></label></>);
else if(step===5)body=page('Settings & functional impairment','Symptoms are not treated as severity. The simulator records functional impact separately across settings.',<><h3>Settings</h3>{settings.map((x,i)=><Slider key={x} label={x} value={a.settings[i]||0} onChange={value=>update(c=>({...c,settings:{...c.settings,[i]:value}}))}/>)}<h3>Functional impairment</h3>{impairment.map((x,i)=><Slider key={x} label={x} value={a.impairment[i]||0} onChange={value=>update(c=>({...c,impairment:{...c.impairment,[i]:value}}))}/>)}</>);
else if(step===6)body=slider('executive','Executive functioning',executive);
else if(step===7)body=slider('differential','Differential considerations',differential);
else if(step===8)body=page('Collateral information','A second perspective can add useful context. Differences between self-report and observer report do not automatically invalidate either view.',<div className="form-grid"><label>Observer type<select value={a.collateral.type} onChange={e=>update(c=>({...c,collateral:{...c.collateral,type:e.target.value}}))}><option value="">Not entered</option>{['Parent','Partner','Teacher','Friend','Employer','Other'].map(x=><option key={x}>{x}</option>)}</select></label><label className="full">Observer notes<textarea value={a.collateral.note} onChange={e=>update(c=>({...c,collateral:{...c.collateral,note:e.target.value}}))}/></label></div>);
else if(step===9)body=page('Response review','Neutral checks identify input that may benefit from clarification; they never determine whether a response is valid.',<div className="note"><b>Ready for a teaching report.</b> The final report keeps symptom frequency, developmental evidence, functional impact, and differential considerations distinct. It does not generate an ADHD percentage.</div>);
else body=<Report assessment={a} onClear={clear}/>;
return <><header><div className="brand"><span>A</span><div>Axis Clinical Learning<small>ADHD assessment simulator</small></div></div><label className="student"><input type="checkbox" checked={student} onChange={e=>setStudent(e.target.checked)}/> Student guidance</label></header><main className={student?'student-mode':''}>{step===10?body:<div className="shell"><aside><div className="rail"><div className="eyebrow">Structured assessment</div><h3>Clinical pathway</h3><div className="progress"><i style={{width:`${percentage}%`}}/></div><p>Progress <b>{percentage}%</b></p><ol>{steps.map((s,i)=><li key={s} className={i===step?'active':i<step?'done':''}>{s}</li>)}</ol></div></aside><section className="sheet"><span className="section-number">{String(step).padStart(2,'0')} / {steps[step]}</span>{body}{step>0&&<div className="actions"><button className="secondary" onClick={()=>setStep(s=>s-1)}>Back</button><button onClick={next}>Continue</button></div>}</section></div>}</main><footer>Educational screening and clinical-reasoning simulation — not a diagnostic device. A qualified clinician must make any diagnosis or treatment decision.</footer></>}
function page(title:string,description:string,children:ReactNode){return <><h2>{title}</h2><p className="lede">{description}</p>{children}</>}
